---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "https://endowl.github.io/blog/"
title: "Endowl Blog"
canonifyurls: true
theme: "Lanyon"
...
